# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cowboy Coder
email: cowboycodervn@gmail.com
tagline: "To code like a Cowboy!"
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cowboycoder.tech" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  tranHieuDev23

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-paginate-v2

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults: 
  - 
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: <!-- excerpt-end -->
      permalink: /:categories/:title
      thumbnail: "default-thumbnail.jpg"
  -
    scope:
      path: "_posts/algorithm/data-structure"
      type: "posts"
    values:
      categories: algorithm data-structure
  -
    scope:
      path: "_posts/algorithm/basic"
      type: "posts"
    values:
      categories: algorithm basic
  -
    scope:
      path: "_posts/algorithm/dp"
      type: "posts"
    values:
      categories: algorithm dp
  -
    scope:
      path: "_posts/algorithm/graph"
      type: "posts"
    values:
      categories: algorithm graph
  -
    scope:
      path: "_posts/algorithm/math"
      type: "posts"
    values:
      categories: algorithm math
  -
    scope:
      path: "_posts/algorithm/other"
      type: "posts"
    values:
      categories: algorithm other
  -
    scope:
      path: "_posts/algorithm/string"
      type: "posts"
    values:
      categories: algorithm string
  -
    scope:
      path: "_posts/programming/c_cpp"
      type: "posts"
    values:
      categories: programming c_cpp
  -
    scope:
      path: "_posts/programming/java"
      type: "posts"
    values:
      categories: programming java
  -
    scope:
      path: "_posts/programming/web"
      type: "posts"
    values:
      categories: programming web
  -
    scope:
      path: "_posts/exercises"
      type: "posts"
    values:
      categories: exercises
  -
    scope:
      path: "_posts/misc"
      type: "posts"
    values:
      categories: misc

pagination:
  enabled: true
  per_page: 10
  trail:
    before: 2
    after: 2
  sort_field: 'date'
  sort_reverse: true

autopages:
  enabled: true
  categories:
    layouts: 
      - "archive.html"
    title: ":cat"
    permalink: "/categories/:cat"
  tags:
    layouts: 
      - "archive.html"
    title: ":tag"
    permalink: "/tags/:tag"

